/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "primary-strong": "var(--color-primary-strong)",
        "primary-soft": "var(--color-primary-soft)",
        secondary: "var(--color-secondary)",
        accent: "var(--color-accent)",
        "accent-soft": "var(--color-accent-soft)",
        "accent-border": "var(--color-accent-border)",
        success: "var(--color-success)",
        "success-soft": "var(--color-success-soft)",
        "success-border": "var(--color-success-border)",
        danger: "var(--color-danger)",
        "danger-soft": "var(--color-danger-soft)",
        "danger-border": "var(--color-danger-border)",
        warn: "var(--color-warn)",
        surface: "var(--color-bg-surface)",
        "surface-soft": "var(--color-bg-surface-soft)",
        page: "var(--color-bg-page)",
        control: "var(--color-bg-control)",
        overlay: "var(--color-overlay)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "text-on-accent": "var(--color-text-on-accent)",
        "snackbar-info": "var(--color-snackbar-info)",
        "snackbar-success": "var(--color-snackbar-success)",
        "snackbar-warn": "var(--color-snackbar-warn)",
        "snackbar-error": "var(--color-snackbar-error)",
        "border-default": "var(--color-border-default)",
        "border-strong": "var(--color-border-strong)",
        "border-soft": "var(--color-border-soft)",
        "border-accent": "var(--color-border-accent)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        modal: "var(--shadow-modal)",
      },
      fontFamily: {
        base: "var(--font-family-base)",
      },
    },
  },
  plugins: [],
};
