const hasOwn = Object.prototype.hasOwnProperty;

function createTheme(label, colorScheme, tokens) {
  return {
    label,
    colorScheme,
    ...tokens,
  };
}

const LIGHT_BASE = {
  "--color-primary": "#375dfb",
  "--color-primary-strong": "#2346ca",
  "--color-primary-soft": "#eef2ff",
  "--color-secondary": "#2f448f",
  "--color-accent": "#6f7fe8",
  "--color-accent-soft": "#edf0ff",
  "--color-accent-border": "#b9c8ff",
  "--color-success": "#157347",
  "--color-success-soft": "#c9efda",
  "--color-success-border": "#67c48d",
  "--color-danger": "#b42318",
  "--color-danger-soft": "#ffeff0",
  "--color-danger-border": "#ffced1",
  "--color-warn": "#a16207",
  "--color-bg-page": "#f4f7ff",
  "--color-bg-page-gradient":
    "radial-gradient(circle at top, #e8eeff, #f7f9ff 42%, #f4f7ff 100%)",
  "--color-bg-surface": "#ffffff",
  "--color-bg-surface-soft": "#f8faff",
  "--color-bg-control": "#eef2ff",
  "--color-overlay": "rgba(24, 33, 62, 0.35)",
  "--color-text-primary": "#1a2340",
  "--color-text-secondary": "#64719a",
  "--color-text-muted": "#667395",
  "--color-text-on-accent": "#ffffff",
  "--color-snackbar-info": "#1f4fbf",
  "--color-snackbar-success": "#197a43",
  "--color-snackbar-warn": "#a16207",
  "--color-snackbar-error": "#b42318",
  "--border-strong": "1px solid #d5deff",
  "--border-default": "1px solid #dce5ff",
  "--border-soft": "1px solid #e4eaff",
  "--border-accent": "1px solid #b9c8ff",
  "--shadow-card": "0 14px 30px -24px rgba(31, 59, 159, 0.55)",
  "--shadow-modal": "0 20px 34px -20px rgba(31, 59, 159, 0.55)",
};

const DARK_BASE = {
  "--color-primary": "#6d87db",
  "--color-primary-strong": "#4e6bd3",
  "--color-primary-soft": "#1b2646",
  "--color-secondary": "#d7e2ff",
  "--color-accent": "#89a5ff",
  "--color-accent-soft": "#1a2d57",
  "--color-accent-border": "#6582d0",
  "--color-success": "#68d391",
  "--color-success-soft": "#1f5637",
  "--color-success-border": "#3da56a",
  "--color-danger": "#ffd7de",
  "--color-danger-soft": "#3b1d2a",
  "--color-danger-border": "#8d465f",
  "--color-warn": "#d7b46b",
  "--color-bg-page": "#0f1424",
  "--color-bg-page-gradient":
    "radial-gradient(circle at top, #17203a, #11172b 45%, #0f1424 100%)",
  "--color-bg-surface": "#171f36",
  "--color-bg-surface-soft": "#121a2f",
  "--color-bg-control": "#1b2646",
  "--color-overlay": "rgba(8, 12, 24, 0.6)",
  "--color-text-primary": "#e9efff",
  "--color-text-secondary": "#c0ccef",
  "--color-text-muted": "#aebbe3",
  "--color-text-on-accent": "#eef3ff",
  "--color-snackbar-info": "#385fb9",
  "--color-snackbar-success": "#2f9b63",
  "--color-snackbar-warn": "#b78730",
  "--color-snackbar-error": "#c55a6f",
  "--border-strong": "1px solid #3a4c7f",
  "--border-default": "1px solid #2f3f6b",
  "--border-soft": "1px solid #32416d",
  "--border-accent": "1px solid #6582d0",
  "--shadow-card": "0 16px 30px -22px rgba(0, 0, 0, 0.6)",
  "--shadow-modal": "0 20px 34px -20px rgba(0, 0, 0, 0.7)",
};

export const THEME_DEFINITIONS = {
  light: createTheme("Light", "light", LIGHT_BASE),
  dark: createTheme("Dark", "dark", DARK_BASE),
  atlasi: createTheme("Atlasi", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#8b5cf6",
    "--color-primary-strong": "#7c3aed",
    "--color-primary-soft": "#f1eafe",
    "--color-secondary": "#6d28d9",
    "--color-accent": "#f472b6",
    "--color-accent-soft": "#fde7f3",
    "--color-accent-border": "#f0abfc",
    "--color-success": "#3a8f72",
    "--color-success-soft": "#dff4ed",
    "--color-success-border": "#79c7ac",
    "--color-danger": "#c2417a",
    "--color-danger-soft": "#fde4ef",
    "--color-danger-border": "#f4a8c9",
    "--color-warn": "#b76a17",
    "--color-bg-page": "#f7f2ff",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #f0dcff, #faf6ff 44%, #f7f2ff 100%)",
    "--color-bg-surface": "#fffaff",
    "--color-bg-surface-soft": "#faf5ff",
    "--color-bg-control": "#f3eaff",
    "--color-overlay": "rgba(68, 34, 104, 0.22)",
    "--color-text-primary": "#251437",
    "--color-text-secondary": "#684c82",
    "--color-text-muted": "#7f6697",
    "--color-snackbar-info": "#5b4acb",
    "--color-snackbar-success": "#2e8c6f",
    "--color-snackbar-warn": "#b46b1d",
    "--color-snackbar-error": "#bf3f6d",
    "--border-strong": "1px solid #e0c5ff",
    "--border-default": "1px solid #ead7ff",
    "--border-soft": "1px solid #f0e4ff",
    "--border-accent": "1px solid #d4b4ff",
    "--shadow-card": "0 16px 32px -24px rgba(95, 59, 147, 0.5)",
    "--shadow-modal": "0 20px 34px -20px rgba(95, 59, 147, 0.55)",
  }),
  "matcha-green": createTheme("Matcha Green", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#4f8f5a",
    "--color-primary-strong": "#3f7348",
    "--color-primary-soft": "#e6f3ea",
    "--color-secondary": "#2f6140",
    "--color-accent": "#86b57b",
    "--color-accent-soft": "#edf7e8",
    "--color-accent-border": "#b7d5ac",
    "--color-success": "#2f8f55",
    "--color-success-soft": "#e4f6ea",
    "--color-success-border": "#83c999",
    "--color-danger": "#af4f50",
    "--color-danger-soft": "#fbe8e8",
    "--color-danger-border": "#e4a3a0",
    "--color-warn": "#9d6b14",
    "--color-bg-page": "#f3faf2",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #e0f2e0, #f8fcf6 42%, #f3faf2 100%)",
    "--color-bg-surface": "#fbfffb",
    "--color-bg-surface-soft": "#f4faf3",
    "--color-bg-control": "#eaf5e8",
    "--color-overlay": "rgba(27, 73, 43, 0.18)",
    "--color-text-primary": "#1f3326",
    "--color-text-secondary": "#526758",
    "--color-text-muted": "#6f8578",
    "--color-snackbar-info": "#47796a",
    "--color-snackbar-success": "#2f8f55",
    "--color-snackbar-warn": "#a06b18",
    "--color-snackbar-error": "#b45b5c",
    "--border-strong": "1px solid #d3e8d0",
    "--border-default": "1px solid #e0f0dd",
    "--border-soft": "1px solid #e8f3e7",
    "--border-accent": "1px solid #bed7b7",
    "--shadow-card": "0 16px 32px -24px rgba(60, 116, 79, 0.45)",
    "--shadow-modal": "0 20px 34px -20px rgba(60, 116, 79, 0.5)",
  }),
  turquoise: createTheme("Turquoise", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#1f93a8",
    "--color-primary-strong": "#167386",
    "--color-primary-soft": "#e4f7fa",
    "--color-secondary": "#13606f",
    "--color-accent": "#4ac6c1",
    "--color-accent-soft": "#e7fbfa",
    "--color-accent-border": "#97e1db",
    "--color-success": "#2b8f79",
    "--color-success-soft": "#def5f1",
    "--color-success-border": "#76d0bf",
    "--color-danger": "#af5468",
    "--color-danger-soft": "#fbe7ec",
    "--color-danger-border": "#e3a1af",
    "--color-warn": "#a96a1d",
    "--color-bg-page": "#eefcff",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #d8f9ff, #f6fdff 44%, #eefcff 100%)",
    "--color-bg-surface": "#fbffff",
    "--color-bg-surface-soft": "#f2fbfd",
    "--color-bg-control": "#e0f5f8",
    "--color-overlay": "rgba(14, 68, 78, 0.2)",
    "--color-text-primary": "#17363c",
    "--color-text-secondary": "#4f6b71",
    "--color-text-muted": "#69888f",
    "--color-snackbar-info": "#1f7d95",
    "--color-snackbar-success": "#2b8f79",
    "--color-snackbar-warn": "#a96a1d",
    "--color-snackbar-error": "#b45a6d",
    "--border-strong": "1px solid #cceef3",
    "--border-default": "1px solid #dbf2f5",
    "--border-soft": "1px solid #e7f7f9",
    "--border-accent": "1px solid #a8e1e9",
    "--shadow-card": "0 16px 32px -24px rgba(23, 105, 118, 0.45)",
    "--shadow-modal": "0 20px 34px -20px rgba(23, 105, 118, 0.5)",
  }),
  pastel: createTheme("Pastel", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#7d7fbf",
    "--color-primary-strong": "#6467ab",
    "--color-primary-soft": "#efeffc",
    "--color-secondary": "#666c98",
    "--color-accent": "#cda4ff",
    "--color-accent-soft": "#f7f0ff",
    "--color-accent-border": "#d7c0ff",
    "--color-success": "#5d9a87",
    "--color-success-soft": "#e8f6f1",
    "--color-success-border": "#9ad1c1",
    "--color-danger": "#c07b8d",
    "--color-danger-soft": "#fdeaf0",
    "--color-danger-border": "#efb4c0",
    "--color-warn": "#b59257",
    "--color-bg-page": "#f8f7fc",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #f2ebff, #fcfbff 45%, #f8f7fc 100%)",
    "--color-bg-surface": "#ffffff",
    "--color-bg-surface-soft": "#faf8ff",
    "--color-bg-control": "#f0ecfb",
    "--color-overlay": "rgba(91, 95, 141, 0.2)",
    "--color-text-primary": "#2a2f4f",
    "--color-text-secondary": "#646b8d",
    "--color-text-muted": "#7d849e",
    "--color-snackbar-info": "#6d7ccf",
    "--color-snackbar-success": "#63a48f",
    "--color-snackbar-warn": "#b28a50",
    "--color-snackbar-error": "#be7486",
    "--border-strong": "1px solid #e1ddf6",
    "--border-default": "1px solid #ebe7fb",
    "--border-soft": "1px solid #f1effc",
    "--border-accent": "1px solid #d5d0f3",
    "--shadow-card": "0 16px 32px -24px rgba(109, 117, 175, 0.45)",
    "--shadow-modal": "0 20px 34px -20px rgba(109, 117, 175, 0.5)",
  }),
  "forest-green": createTheme("Forest Green", "dark", {
    ...DARK_BASE,
    "--color-primary": "#74b88a",
    "--color-primary-strong": "#4ea36a",
    "--color-primary-soft": "#1f3d2b",
    "--color-secondary": "#d4f1dc",
    "--color-accent": "#97d6a8",
    "--color-accent-soft": "#183525",
    "--color-accent-border": "#76b88d",
    "--color-success": "#8de0a7",
    "--color-success-soft": "#1e4a32",
    "--color-success-border": "#54a66f",
    "--color-danger": "#ffb6b4",
    "--color-danger-soft": "#40232a",
    "--color-danger-border": "#a45c64",
    "--color-warn": "#d5b56d",
    "--color-bg-page": "#0d1c15",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #173226, #102219 45%, #0d1c15 100%)",
    "--color-bg-surface": "#15261d",
    "--color-bg-surface-soft": "#111d17",
    "--color-bg-control": "#1d3126",
    "--color-overlay": "rgba(4, 17, 11, 0.65)",
    "--color-text-primary": "#ecf7ef",
    "--color-text-secondary": "#bfd1c1",
    "--color-text-muted": "#9fb2a2",
    "--color-text-on-accent": "#f2fff5",
    "--color-snackbar-info": "#5b8d70",
    "--color-snackbar-success": "#4ea36a",
    "--color-snackbar-warn": "#c89c3d",
    "--color-snackbar-error": "#ce6f72",
    "--border-strong": "1px solid #2e4a3b",
    "--border-default": "1px solid #23382d",
    "--border-soft": "1px solid #284033",
    "--border-accent": "1px solid #4a7d5f",
    "--shadow-card": "0 16px 30px -22px rgba(0, 0, 0, 0.72)",
    "--shadow-modal": "0 20px 34px -20px rgba(0, 0, 0, 0.8)",
  }),
  dawn: createTheme("Dawn", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#f08b52",
    "--color-primary-strong": "#df6c33",
    "--color-primary-soft": "#fff0e7",
    "--color-secondary": "#b85c37",
    "--color-accent": "#ffc28f",
    "--color-accent-soft": "#fff5ed",
    "--color-accent-border": "#f6c29c",
    "--color-success": "#4f9b75",
    "--color-success-soft": "#e7f6ef",
    "--color-success-border": "#96d0b1",
    "--color-danger": "#c7645a",
    "--color-danger-soft": "#fdeceb",
    "--color-danger-border": "#f0b2a8",
    "--color-warn": "#ca7a18",
    "--color-bg-page": "#fff6ef",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #ffe3ca, #fffaf6 46%, #fff6ef 100%)",
    "--color-bg-surface": "#fffdfb",
    "--color-bg-surface-soft": "#fff7f0",
    "--color-bg-control": "#ffebdb",
    "--color-overlay": "rgba(113, 63, 27, 0.18)",
    "--color-text-primary": "#402719",
    "--color-text-secondary": "#7a5c49",
    "--color-text-muted": "#8e7461",
    "--color-snackbar-info": "#d67a40",
    "--color-snackbar-success": "#4f9b75",
    "--color-snackbar-warn": "#ca7a18",
    "--color-snackbar-error": "#c7645a",
    "--border-strong": "1px solid #f0d4c0",
    "--border-default": "1px solid #f6e1d2",
    "--border-soft": "1px solid #faeadf",
    "--border-accent": "1px solid #efc7ab",
    "--shadow-card": "0 16px 32px -24px rgba(202, 122, 24, 0.42)",
    "--shadow-modal": "0 20px 34px -20px rgba(202, 122, 24, 0.48)",
  }),
  moonlight: createTheme("Moonlight", "dark", {
    ...DARK_BASE,
    "--color-primary": "#9ab2ff",
    "--color-primary-strong": "#7996ff",
    "--color-primary-soft": "#1b2849",
    "--color-secondary": "#d8e3ff",
    "--color-accent": "#c9d6ff",
    "--color-accent-soft": "#15213c",
    "--color-accent-border": "#8ea6ff",
    "--color-success": "#80d2ab",
    "--color-success-soft": "#183a33",
    "--color-success-border": "#4d9c7d",
    "--color-danger": "#ffb4c1",
    "--color-danger-soft": "#3a2030",
    "--color-danger-border": "#a9657a",
    "--color-warn": "#ddb56b",
    "--color-bg-page": "#0a1120",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #182242, #0e1630 42%, #0a1120 100%)",
    "--color-bg-surface": "#121b33",
    "--color-bg-surface-soft": "#0e162a",
    "--color-bg-control": "#1b2747",
    "--color-overlay": "rgba(5, 9, 24, 0.66)",
    "--color-text-primary": "#eef3ff",
    "--color-text-secondary": "#c7d3ef",
    "--color-text-muted": "#a3b0d1",
    "--color-text-on-accent": "#f7faff",
    "--color-snackbar-info": "#6d8be0",
    "--color-snackbar-success": "#4d9c7d",
    "--color-snackbar-warn": "#c89f45",
    "--color-snackbar-error": "#cf6f86",
    "--border-strong": "1px solid #314064",
    "--border-default": "1px solid #223151",
    "--border-soft": "1px solid #27385b",
    "--border-accent": "1px solid #6d8be0",
    "--shadow-card": "0 16px 32px -22px rgba(0, 0, 0, 0.7)",
    "--shadow-modal": "0 20px 34px -20px rgba(0, 0, 0, 0.82)",
  }),
  oak: createTheme("Oak", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#9b6a43",
    "--color-primary-strong": "#7c4f2f",
    "--color-primary-soft": "#f4e8dc",
    "--color-secondary": "#6d4b31",
    "--color-accent": "#c9a77e",
    "--color-accent-soft": "#fbf2e9",
    "--color-accent-border": "#dec3a5",
    "--color-success": "#4f8a6a",
    "--color-success-soft": "#e8f4ef",
    "--color-success-border": "#91c3aa",
    "--color-danger": "#b55c54",
    "--color-danger-soft": "#fdeeea",
    "--color-danger-border": "#e1b0a7",
    "--color-warn": "#a97a3a",
    "--color-bg-page": "#f9f4ee",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #efe0cf, #fcf9f5 45%, #f9f4ee 100%)",
    "--color-bg-surface": "#fffdfa",
    "--color-bg-surface-soft": "#faf4ee",
    "--color-bg-control": "#f2e5d7",
    "--color-overlay": "rgba(92, 64, 39, 0.2)",
    "--color-text-primary": "#3c2a1d",
    "--color-text-secondary": "#745a48",
    "--color-text-muted": "#8a725f",
    "--color-snackbar-info": "#8c6d52",
    "--color-snackbar-success": "#4f8a6a",
    "--color-snackbar-warn": "#a97a3a",
    "--color-snackbar-error": "#b55c54",
    "--border-strong": "1px solid #e1d4c5",
    "--border-default": "1px solid #ece1d5",
    "--border-soft": "1px solid #f2e8df",
    "--border-accent": "1px solid #d7b99d",
    "--shadow-card": "0 16px 32px -24px rgba(124, 79, 47, 0.42)",
    "--shadow-modal": "0 20px 34px -20px rgba(124, 79, 47, 0.48)",
  }),
  "sea-salt": createTheme("Sea Salt", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#6f859f",
    "--color-primary-strong": "#52657f",
    "--color-primary-soft": "#edf3f7",
    "--color-secondary": "#475a74",
    "--color-accent": "#91a5bf",
    "--color-accent-soft": "#f5f8fb",
    "--color-accent-border": "#c0d0e3",
    "--color-success": "#4f8d7f",
    "--color-success-soft": "#e7f4f0",
    "--color-success-border": "#92c9bc",
    "--color-danger": "#b06463",
    "--color-danger-soft": "#fcefeb",
    "--color-danger-border": "#e4b1b0",
    "--color-warn": "#a88452",
    "--color-bg-page": "#f3f6f8",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #e2eaf0, #fafcfe 45%, #f3f6f8 100%)",
    "--color-bg-surface": "#ffffff",
    "--color-bg-surface-soft": "#f7fafc",
    "--color-bg-control": "#e8eff5",
    "--color-overlay": "rgba(32, 46, 62, 0.2)",
    "--color-text-primary": "#263442",
    "--color-text-secondary": "#5d6b79",
    "--color-text-muted": "#74828e",
    "--color-snackbar-info": "#5e7f9c",
    "--color-snackbar-success": "#4f8d7f",
    "--color-snackbar-warn": "#a88452",
    "--color-snackbar-error": "#b06463",
    "--border-strong": "1px solid #dbe5ed",
    "--border-default": "1px solid #e7eef3",
    "--border-soft": "1px solid #eef3f7",
    "--border-accent": "1px solid #c6d4e0",
    "--shadow-card": "0 16px 32px -24px rgba(82, 101, 127, 0.42)",
    "--shadow-modal": "0 20px 34px -20px rgba(82, 101, 127, 0.48)",
  }),
  "citrus-zest": createTheme("Citrus Zest", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#c9a30c",
    "--color-primary-strong": "#a98205",
    "--color-primary-soft": "#fff7d7",
    "--color-secondary": "#727100",
    "--color-accent": "#8cc63e",
    "--color-accent-soft": "#f1f9db",
    "--color-accent-border": "#c6e28d",
    "--color-success": "#5f9d45",
    "--color-success-soft": "#edf8e5",
    "--color-success-border": "#a6d381",
    "--color-danger": "#b4634f",
    "--color-danger-soft": "#fcefe8",
    "--color-danger-border": "#e6b3a3",
    "--color-warn": "#c08a08",
    "--color-bg-page": "#fffbed",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #fff0a8, #fffdf4 44%, #fffbed 100%)",
    "--color-bg-surface": "#fffefa",
    "--color-bg-surface-soft": "#fff9ea",
    "--color-bg-control": "#fff2c9",
    "--color-overlay": "rgba(112, 91, 14, 0.18)",
    "--color-text-primary": "#3f3710",
    "--color-text-secondary": "#756a37",
    "--color-text-muted": "#8a7f4e",
    "--color-snackbar-info": "#9a8b28",
    "--color-snackbar-success": "#5f9d45",
    "--color-snackbar-warn": "#c08a08",
    "--color-snackbar-error": "#b4634f",
    "--border-strong": "1px solid #eadf9a",
    "--border-default": "1px solid #f1e8ba",
    "--border-soft": "1px solid #f7f0d0",
    "--border-accent": "1px solid #dfce78",
    "--shadow-card": "0 16px 32px -24px rgba(156, 131, 15, 0.42)",
    "--shadow-modal": "0 20px 34px -20px rgba(156, 131, 15, 0.48)",
  }),
  lavender: createTheme("Lavender", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#8a79c6",
    "--color-primary-strong": "#715eb4",
    "--color-primary-soft": "#efebfb",
    "--color-secondary": "#5f5b91",
    "--color-accent": "#bba7eb",
    "--color-accent-soft": "#f7f3ff",
    "--color-accent-border": "#d0c0f2",
    "--color-success": "#5b8b7f",
    "--color-success-soft": "#e7f4f1",
    "--color-success-border": "#97c5ba",
    "--color-danger": "#bf7488",
    "--color-danger-soft": "#fdebf0",
    "--color-danger-border": "#e4b0c0",
    "--color-warn": "#ab8451",
    "--color-bg-page": "#f7f4fb",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #ece5ff, #fdfcff 45%, #f7f4fb 100%)",
    "--color-bg-surface": "#ffffff",
    "--color-bg-surface-soft": "#faf7ff",
    "--color-bg-control": "#ece5fb",
    "--color-overlay": "rgba(82, 68, 123, 0.2)",
    "--color-text-primary": "#2f2947",
    "--color-text-secondary": "#655f80",
    "--color-text-muted": "#80799a",
    "--color-snackbar-info": "#6f77ca",
    "--color-snackbar-success": "#5b8b7f",
    "--color-snackbar-warn": "#ab8451",
    "--color-snackbar-error": "#bf7488",
    "--border-strong": "1px solid #e0d7f2",
    "--border-default": "1px solid #ece6f8",
    "--border-soft": "1px solid #f3effb",
    "--border-accent": "1px solid #d6c8ef",
    "--shadow-card": "0 16px 32px -24px rgba(113, 94, 180, 0.42)",
    "--shadow-modal": "0 20px 34px -20px rgba(113, 94, 180, 0.48)",
  }),
  "coral-rose": createTheme("Coral Rose", "light", {
    ...LIGHT_BASE,
    "--color-primary": "#e46b72",
    "--color-primary-strong": "#cf5560",
    "--color-primary-soft": "#fff0f1",
    "--color-secondary": "#aa4d5b",
    "--color-accent": "#ffa381",
    "--color-accent-soft": "#fff4ef",
    "--color-accent-border": "#ffc1b0",
    "--color-success": "#4c9a8a",
    "--color-success-soft": "#e8f5f2",
    "--color-success-border": "#94cec0",
    "--color-danger": "#b94e5f",
    "--color-danger-soft": "#fdebee",
    "--color-danger-border": "#e6a7b0",
    "--color-warn": "#c06f20",
    "--color-bg-page": "#fff6f5",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #ffd7d4, #fffaf8 45%, #fff6f5 100%)",
    "--color-bg-surface": "#ffffff",
    "--color-bg-surface-soft": "#fff8f7",
    "--color-bg-control": "#ffe7e4",
    "--color-overlay": "rgba(122, 54, 62, 0.18)",
    "--color-text-primary": "#401f28",
    "--color-text-secondary": "#7b4b55",
    "--color-text-muted": "#94626b",
    "--color-snackbar-info": "#cf6d76",
    "--color-snackbar-success": "#4c9a8a",
    "--color-snackbar-warn": "#c06f20",
    "--color-snackbar-error": "#b94e5f",
    "--border-strong": "1px solid #f0d2d4",
    "--border-default": "1px solid #f6e3e5",
    "--border-soft": "1px solid #faecee",
    "--border-accent": "1px solid #efb2b7",
    "--shadow-card": "0 16px 32px -24px rgba(194, 83, 98, 0.42)",
    "--shadow-modal": "0 20px 34px -20px rgba(194, 83, 98, 0.48)",
  }),
  "emerald-dusk": createTheme("Emerald Dusk", "dark", {
    ...DARK_BASE,
    "--color-primary": "#6ed0b8",
    "--color-primary-strong": "#48b79d",
    "--color-primary-soft": "#173a35",
    "--color-secondary": "#d2f6eb",
    "--color-accent": "#8fe0cb",
    "--color-accent-soft": "#112d2a",
    "--color-accent-border": "#4db6a3",
    "--color-success": "#8ce0a1",
    "--color-success-soft": "#163c2c",
    "--color-success-border": "#59a872",
    "--color-danger": "#ffb9bf",
    "--color-danger-soft": "#3d2227",
    "--color-danger-border": "#a7656b",
    "--color-warn": "#d7b96d",
    "--color-bg-page": "#081816",
    "--color-bg-page-gradient":
      "radial-gradient(circle at top, #102823, #0a1817 44%, #081816 100%)",
    "--color-bg-surface": "#11241f",
    "--color-bg-surface-soft": "#0c1a17",
    "--color-bg-control": "#17312b",
    "--color-overlay": "rgba(2, 12, 10, 0.68)",
    "--color-text-primary": "#edf8f3",
    "--color-text-secondary": "#bfd7d0",
    "--color-text-muted": "#9db8b0",
    "--color-text-on-accent": "#f4fff9",
    "--color-snackbar-info": "#62b5a1",
    "--color-snackbar-success": "#49b178",
    "--color-snackbar-warn": "#c9a64c",
    "--color-snackbar-error": "#d16e79",
    "--border-strong": "1px solid #24443d",
    "--border-default": "1px solid #19322d",
    "--border-soft": "1px solid #1c3a34",
    "--border-accent": "1px solid #49b59f",
    "--shadow-card": "0 16px 30px -22px rgba(0, 0, 0, 0.72)",
    "--shadow-modal": "0 20px 34px -20px rgba(0, 0, 0, 0.82)",
  }),
};

export const THEME_OPTIONS = Object.entries(THEME_DEFINITIONS).map(
  ([value, theme]) => ({
    value,
    label: theme.label,
  }),
);

export function isTheme(value) {
  return Boolean(value && hasOwn.call(THEME_DEFINITIONS, value));
}

export function normalizeTheme(value) {
  return isTheme(value) ? value : "light";
}

export function getThemeLabel(theme) {
  return THEME_DEFINITIONS[normalizeTheme(theme)]?.label || "Light";
}

export function getThemeMeta(theme) {
  return THEME_DEFINITIONS[normalizeTheme(theme)] || THEME_DEFINITIONS.light;
}

function readStoredTheme() {
  if (typeof window === "undefined") return null;

  try {
    return (
      window.localStorage.getItem("dr_theme") ||
      window.sessionStorage.getItem("dr_theme")
    );
  } catch {
    return null;
  }
}

export function getSavedTheme() {
  if (typeof window === "undefined") return "light";

  const savedTheme = readStoredTheme();
  if (isTheme(savedTheme)) return savedTheme;

  if (savedTheme === "dark" || savedTheme === "light") return savedTheme;

  return window.matchMedia?.("(prefers-color-scheme: dark)").matches
    ? "dark"
    : "light";
}

export function setThemeStorage(theme) {
  if (typeof window === "undefined") return;

  try {
    window.localStorage.setItem("dr_theme", normalizeTheme(theme));
  } catch {
    // Ignore storage failures and keep the active theme in memory.
  }
}

export function applyThemeToDocument(theme) {
  if (typeof document === "undefined") return;

  const normalizedTheme = normalizeTheme(theme);
  const themeDefinition = getThemeMeta(normalizedTheme);
  const root = document.documentElement;
  const body = document.body;

  root.setAttribute("data-theme", normalizedTheme);
  body?.setAttribute("data-theme", normalizedTheme);
  root.style.colorScheme = themeDefinition.colorScheme;
  if (body) body.style.colorScheme = themeDefinition.colorScheme;

  Object.entries(themeDefinition).forEach(([key, value]) => {
    if (key === "label" || key === "colorScheme") return;
    root.style.setProperty(key, value);
  });
}
